### ISSUE TITLE
Some data blocks don't trigger on_data

### ISSUE THREAD

**Issue by trollfot** [pyrates/multifruits#5]
I've been using multifruits in Roll and in a test project of mine.
While testing some upload, i found myself a bit puzzled by the result.
I've been using this file for my tests:  https://media.readthedocs.org/pdf/sanic/latest/sanic.pdf
On the 317954 bytes of the file, only a handful (between 15k and 25k) actually are passed on to on_data.
I'm not quite sure what causes it, I didn't dive into the Cython to have a look.
It's easy to reproduce, using Roll for instance:

```
@app.route('/', methods=['POST'])
async def hello(request, response):
   ... test request.files here
```

With the request by cURL:

`curl -X POST -F fileupload=@/path/to/sanic.pdf 127.0.0.1:3579`

**Comment by yohanboniface** [comment]
Thanks for the report!
I'll travel back tomorrow, and thus have a bit more time to deal with this and the Roll story :)
Just to be sure to understand: you can reproduce with any content when using cURL? Or is this specific sanic.pdf file needed to reproduce?

**Comment by trollfot** [comment]
I can reproduce the problem each time I send this particular PDF. I tried with other files, some csv data, some pure binary, it happened once with another file that was pure binary (a mp3 file I think). I only tried via cURL. I'll make a dump of the full request, just to see the multipart created. Maybe the separator appears in the file... I didn't investigate enough

**Comment by yohanboniface** [comment]
can you share the pdf then? :)

**Comment by trollfot** [comment]
It's the one I linked in the error report.
So, after a test, I always read:

```
parse._current.seek(0)
len(parser._current.read())
23658
```
The file in _current is the one I expected to get in full, it never gets "completed" by "on_part_complete".
I can see the header of the part was read correctly:

```
(Pdb) parser._current.filename
'sanic.pdf'
(Pdb) parser._current.params
{b'name': b'fileupload', b'filename': b'sanic.pdf'}
(Pdb) 
```
And I count the length of data fed to the parser as I do it:
```
(Pdb) read
317954
(Pdb) 
```

**Comment by yohanboniface** [comment]
> It's the one I linked in the error report.

Oops, my bad! :s

**Comment by yohanboniface** [comment]
Quick look: the body contain a `0` bytes (`\x00`), which is a NULL bytes for C, so the `len(data)` in cython is "in the cabbage" (sic). Fix may be around the way we pass the bytes to cython.
Going offline now, will continue tomorrow evening.
