### ISSUE TITLE
Invalid processing of small chunks of data

### ISSUE THREAD

**Issue by adontz** [pyrates/multifruits#7]
I think I have found an unexpected behavior.

For the following test data

    data = b'-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-text"\r\n\r\n\xd0\xbf\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x82\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-password"\r\n\r\n\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-radio"\r\n\r\nB\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-color"\r\n\r\n#8000ff\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-date"\r\n\r\n2018-11-08\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-datetime"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-datetime-local"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-email"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-file"; filename="test-\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2-\xd1\x82\xd0\xb5\xd1\x81\xd1\x82.txt"\r\nContent-Type: text/plain\r\n\r\n00 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n01 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n02 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n03 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n04 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n05 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n06 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n07 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n08 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n09 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n10 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n11 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n12 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n13 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n14 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n15 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n16 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n17 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n18 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n19 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n20 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n21 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n22 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n23 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n24 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n25 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n26 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n27 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n28 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n29 TEST!\xe1\x83\xa2\xe1\x83\x94\xe1\x83\xa1\xe1\x83\xa2!\xd0\xa2\xd0\x95\xd0\xa1\xd0\xa2\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-month"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-number"\r\n\r\n13.5\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-range"\r\n\r\n10\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-search"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-tel"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-time"\r\n\r\n11:22\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-url"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-week"\r\n\r\n\r\n-----------------------------281531282519327\r\nContent-Disposition: form-data; name="post-2-submit"\r\n\r\nsubmit\r\n-----------------------------281531282519327--\r\n'

if I call 

    parser.feed_data(data[0:44]) # or any other number less than 44
    parser.feed_data(data[44:])

I get "ValueError: FIRST_BOUNDARY", while

    parser.feed_data(data[0:45])
    parser.feed_data(data[45:])

works just file.

**Comment by yohanboniface** [comment]
Thanks for the report!

This is because the boundary itself is chunked. Work in progress in #8 to fix that issue.

**Comment by yohanboniface** [comment]
Should be fixed with 0.1.4 release https://pypi.org/project/multifruits/
